version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: localhost
    environment:
      KAFKA_CREATE_TOPICS: "Warrior:1:1" #topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafdrop:
    image: thomsch98/kafdrop
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
      - LISTEN=9000
    links:
      - zookeeper
    depends_on:
      - zookeeper
